name: Manual Build of futurerestore for macOS

on:
  workflow_dispatch:

jobs:
  build:
    name: Build futurerestore for macOS
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies via Homebrew
        run: |
          brew install automake libtool pkg-config cmake openssl libzip libplist libusbmuxd libimobiledevice

      - name: Clone and build dependencies
        run: |
          mkdir deps && cd deps

          git clone https://github.com/tihmstar/libgeneral
          cd libgeneral && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..

          git clone https://github.com/tihmstar/libfragmentzip
          cd libfragmentzip && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..

          git clone https://github.com/tihmstar/libimg4tool
          cd libimg4tool && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..

          git clone https://github.com/tihmstar/libinsn
          cd libinsn && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..

          git clone https://github.com/tihmstar/liboffsetfinder64
          cd liboffsetfinder64 && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..

          git clone https://github.com/tihmstar/libipatcher
          cd libipatcher && ./autogen.sh && ./configure && make -j && sudo make install
          cd ..
        
      - name: Run Build script
        run: |
          ./build.sh

      - name: Upload futurerestore binary
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-macos-x86_64
          path: ./futurerestore
